# Generated by Django 5.2.2 on 2025-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
