# Generated by Django 5.2.2 on 2025-07-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assigntask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigntask',
            old_name='student',
            new_name='approved_id',
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
