# Generated by Django 5.2.2 on 2025-07-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('assignmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assigntask')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
