# Generated by Django 5.2.2 on 2025-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comments_is_rated_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_rated',
        ),
        migrations.AddField(
            model_name='assigntask',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
